### ISSUE TITLE
Minor issues with libcouchbase

### ISSUE THREAD

**Issue by stakach** [neelance/ffi_gen#39]
I had to edit some code for the generator to work and not sure what the effect of my code changes are, hence why this isn't a pull request

On OSX, I cloned [libcouchbase](https://github.com/couchbase/libcouchbase) and built it as per the instructions on that repo

Then I run the following in `irb`:

``` ruby

require "ffi_gen"

FFIGen.generate(
  module_name: "Libcouchbase::Ext",
  ffi_lib:     "libcouchbase",
  headers:     ["./include/libcouchbase/couchbase.h"],
# Needed the header stdarg.h which I found on my system here
   cflags:      ["-I/System/Library/Frameworks/Kernel.framework/Versions/A/Headers"],
  prefixes:    ["LCB_", "lcb_"],
  output:      "libcouchbase.rb"
)

```

The following code had errors:

``` ruby
# NoMethodError: undefined method `parts' for nil:NilClass
#    from /Users/steve/.rvm/gems/ruby-2.1.5/gems/ffi_gen-1.2.0/lib/ffi_gen.rb:447:in `read_declaration'
# -- I fixed ffi_gen.rb:447 by adding the  && name
last_nested_declaration.name ||= Name.new(name.parts + field_name.parts) if last_nested_declaration && name
```

then

``` ruby
# NoMethodError: undefined method `to_ruby_classname' for nil:NilClass
#   from /Users/steve/.rvm/gems/ruby-2.1.5/gems/ffi_gen-1.2.0/lib/ffi_gen/ruby_output.rb:134:in `ruby_name'
# -- I fixed ruby_output.rb:134 by adding the check for nil
@ruby_name ||= @name ? @name.to_ruby_classname : nil
```

Hopefully you find this useful and thanks for creating this awesome gem!

**Comment by stakach** [comment]
I should note that it did lead to a few un-named classed - due to the anonymous union

``` c
typedef struct {
    const void *key;
    lcb_SIZE nkey;
    lcb_U64 value; /**< Current numerical value of the counter */
    lcb_cas_t cas;
    /** Synctoken for mutation. This is used with N1QL and durability */
    const lcb_SYNCTOKEN *synctoken;
} lcb_ARITHRESPv0;

typedef struct {
    int version;
    union {
        lcb_ARITHRESPv0 v0;
    } v;
} lcb_arithmetic_resp_t;
```

resulted in:

``` ruby
  class ARITHRESPv0 < FFI::Struct
    layout :key, :pointer,
           :nkey, :ulong,
           :value, :ulong_long,
           :cas, :ulong_long,
           :synctoken, SYNCTOKEN
  end

  class  < FFI::Union
    layout :v0, ARITHRESPv0.by_value
  end

  class ArithmeticRespT < FFI::Struct
    layout :version, :int,
           :v, .by_value
  end
```
